### Pytorch tensor & NumPy
Numpy is a ppular scientific Python numerical computing library.
And because of this, pyTorch has functionlity to interact with it.
* Data in Numpy, want in  PyTorch tensor -> `torch.from_numpy(ndarray)`

In [3]:
# NumPy array to tensor
import numpy as np
import torch as tr

In [4]:

array = np.arange(1.0,8.0)
tensor = tr.from_numpy(array).type(tr.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [5]:
array.dtype

dtype('float64')

In [6]:
tensor.dtype

torch.float32

In [7]:
 #  change the value of array, what will this do to `tensor`?
array= array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [8]:
# Tensor to NumPy array
tensor = tr.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Changing the tensor, waht happens to `Tensor_numpy`

In [9]:
tensor = tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out of random)
In short how a neural network learns:
 ` Start with random numbers -> tensor oprations -> Update random numbers to try and make them better representations of the data -> again -> again... `

In [24]:
rep = tr.rand(3,3)
rep

tensor([[0.3241, 0.4225, 0.5973],
        [0.1121, 0.1919, 0.2283],
        [0.3301, 0.1097, 0.8699]])

# These are same but these result are difrient. `rep  = tr.rand(3,3) ==> rep = tr.rand(3,3)`

In [25]:
rep = tr.rand(3,3) 
rep

tensor([[0.8409, 0.6625, 0.9694],
        [0.3090, 0.3127, 0.2526],
        [0.2819, 0.6584, 0.1698]])

### Now I want to do comapre between first_rep and secound_rep
If you do some practice to python we have arithmetic operation to python and we have comparison operation to python. 
if we have `a=5,b=6,c=5`.
if we comapre a == b, the result of `Flase`
and if we compare a == c, the result of comparision is `True`

In [37]:
random_tensor_A = tr.rand(3,4)
random_tensor_B = tr.rand(3,4)
random_tensor_A,'==================',random_tensor_B


(tensor([[0.1390, 0.0981, 0.0553, 0.0434],
         [0.5779, 0.9028, 0.4196, 0.3501],
         [0.8141, 0.4117, 0.4816, 0.8173]]),
 '==================',
 tensor([[0.4152, 0.8311, 0.6440, 0.3035],
         [0.9384, 0.3339, 0.2969, 0.5564],
         [0.4731, 0.0931, 0.7073, 0.4030]]))

### Now co comparision operation

In [38]:
print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


### `Random_Seed`
In ML and KNN, many of operation as random

In [60]:
# Let's make some random but reproducible tensors
Random_seed = 42
tr.manual_seed(Random_seed)
random_tensor_seed_C = tr.rand(5,2)
tr.manual_seed(Random_seed)
random_tensor_seed_D = tr.rand(5,2)


In [61]:
print(random_tensor_seed_C)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009],
        [0.2566, 0.7936],
        [0.9408, 0.1332]])


In [62]:
print(random_tensor_seed_D)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009],
        [0.2566, 0.7936],
        [0.9408, 0.1332]])


In [66]:
print(random_tensor_seed_C == random_tensor_seed_D)

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])


In [67]:
random_tensor_seed_C.T

tensor([[0.8823, 0.3829, 0.3904, 0.2566, 0.9408],
        [0.9150, 0.9593, 0.6009, 0.7936, 0.1332]])