In [2]:
import torch as tr


In [3]:
Tensor1 = tr.tensor([[
                   [1,2,6],
                   [1,4,8],
                   [9,18,27]
                     ]])


In [4]:
Tensor1

tensor([[[ 1,  2,  6],
         [ 1,  4,  8],
         [ 9, 18, 27]]])

In [5]:
Tensor1.shape

torch.Size([1, 3, 3])

In [6]:
Tensor1.ndim

3

### Random tensors
why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.


``start with random numbers -> look at data -> update random number -> look at data -> update numbers``


In [7]:
### Create a random tensor of size (3,5)
random_tensor = tr.rand(3,5)
'Random tensor ---> \n', random_tensor

('Random tensor ---> \n',
 tensor([[0.9566, 0.1911, 0.4842, 0.5245, 0.9484],
         [0.4901, 0.0760, 0.6258, 0.8705, 0.3668],
         [0.8008, 0.5176, 0.5354, 0.6407, 0.7786]]))

In [8]:
'Number of dimenction ',random_tensor.ndim

('Number of dimenction ', 2)

In [9]:
 Random_tensor2 = tr.rand(10,10,10)

In [10]:
Random_tensor2.ndim

3

In [11]:
Random_tensor2.shape

torch.Size([10, 10, 10])

In [12]:
ten_pro = tr.tensor([[[2,3,4],[9,4,4],[0,1,0]]])
ten_pro


tensor([[[2, 3, 4],
         [9, 4, 4],
         [0, 1, 0]]])

In [13]:
ten_pro.ndim

3

In [14]:
ten_pro.shape

torch.Size([1, 3, 3])

In [21]:
ten_pro

tensor([[[2, 3, 4],
         [9, 4, 4],
         [0, 1, 0]]])

In [24]:
# Len's index on our new tensor
ten_pro[0]

tensor([[2, 3, 4],
        [9, 4, 4],
        [0, 1, 0]])

In [25]:
# Let's index on the most inner bracket last dimenction
ten_pro[0][0]

tensor([2, 3, 4])

In [34]:
# You can also uof a target use ":" to select " ALL" of a target dimenction_ in this example we use 0 index
ten_pro[:,0]

tensor([[2, 3, 4]])

In [35]:
# ===>> Now we show 1 index
ten_pro[:,1]

tensor([[9, 4, 4]])

In [36]:
# === >>  Now we show 2 index 
ten_pro[:,2]

tensor([[0, 1, 0]])

In [39]:
#  In this why we can show ALl element's [:,:]
ten_pro[:,:]

tensor([[[2, 3, 4],
         [9, 4, 4],
         [0, 1, 0]]])

In [ ]:
# Find the spcific element 